# --- Ansible Host Inventory Configuration ---
# Replace YOUR_EC2_PUBLIC_IP with your E2 Instance's IP address or public DNS.
# Replace /path/to/your/aws-private-key.pem with the actual local path of your AWS SSH Key.

[jumpbox]
YOUR_EC2_PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=/path/to/your/aws-private-key.pem
